/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrganizationIdImport } from './routes/$organizationId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OrganizationIdRoute = OrganizationIdImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$organizationId': {
      id: '/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof OrganizationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organizationId': typeof OrganizationIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$organizationId': typeof OrganizationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$organizationId': typeof OrganizationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$organizationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$organizationId'
  id: '__root__' | '/' | '/$organizationId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationIdRoute: typeof OrganizationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationIdRoute: OrganizationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$organizationId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$organizationId": {
      "filePath": "$organizationId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
